site_name: Advanced Statistical Mechanics Notes

site_description: |
  Free notes on some selected advanced topics in statistical mechanics.

nav:
  - Preface: 'preface.md'
  - Time Correlation Functions: 'tcf.md'
  - Acknowledgements: 'acknowledgements.md'
theme:
  name: material
  features:
    - navigation.instant
  custom_dir: theme
  palette:
    primary: 'white'
    accent: 'indigo'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.extra
  - abbr
  - footnotes
  - meta

extra_javascript:
  - 'scripts/mathjaxhelper.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - 'https://cdn.plot.ly/plotly-latest.min.js'